### ISSUE TITLE
Trying to make a campaign

### ISSUE THREAD

**Issue by LeiaFox** [Dogeek/rpg-text#23]
not much of an issue with the code itself I would just like some more documentation on how to use it

**Comment by sbordeyne** [comment]
It has been a while since I've worked on this project, last I remember, I still hadn't implemented a lot of needed features.

If you want to make a game with this, you could start by cloning the repository, and editing the map / game assets in the data directory.

There isn't a functional NPC system as of today, so a campaign would be limited to a custom map (the format is pretty self explanatory, you have cells defined by their positions on a grid, and what character the cell is represented as), custom NPCs (but I don't think there is a system to talk to them, or a full implementation of a shop system...), custom loot and monsters (last I recall, I hadn't implemented all of the monsters from D&D, since those are copyrighted, and I don't have the licensing to use them)

**Comment by LeiaFox** [comment]
ok cool thanks
